#define CHH_TITLE               1
#define CHH_BIRTH               2
#define CHH_COMPAT_YB           3
#define CHH_RECT                4
#define CHH_RELOC               5
#define CHH_TS_HOUSE            6
#define CHH_PROG                7
#define CHH_FEMALE              8
#define CHH_MALE                9
#define CH__ASPECT              10
#define CH__ASPECT_HD           11
#define CH__COMP_REL            12
#define CHH_RELOC_DAT           13
#define CH__HOUSE_CS            14
#define CH__HOUSE_HEAD          15
#define CH__HOUSE_SIGN          16
#define CH__HS_SGN_HED          17
#define CH__MIDPT_HD            18
#define CH__MID_ASPE            19
#define CH__MID_ASPT            20
#define CH__MID_PLANET          21
#define CH__MID_HOUSE           22
#define CH__MISC                23
#define CH__PLANET              24
#define CH__PLAN_EXT            25
#define CH__PLAN_HOUSE          26
#define CHP_ASPECT_PRHD         27
#define CHP_MS_HEAD             28
#define CHP_MS_MISC             29
#define CHP_MS_PLANET           30
#define CHP_PRHOUSE_HEAD        31
#define CHP_PROG_NOTE           32
#define CHP_PLAN_HOUSE          33
#define CHR_RETURN_DATA         27
#define CHR_RETURN_HD           28
#define CHR_RETURN_ITM          29
#define CHS_SUMARY_TITLE        1
#define CHS_SCOUT_PL            2
#define CHS_ASPECT_COUNT        3
#define CHS_ELEMENT_COUNT       4
#define CHS_FUNCTIONAL_COUNT    5
#define CHS_GENDER_COUNT        6
#define CHS_HEMISPHERES_COUNT   7
#define CHS_MODAL_COUNT         8
#define CHS_QUALITIES_COUNT     9
#define CHS_SIGN_COUNT          10
#define CHS_HOUSE_COUNT         11
#define CHT_TRANS_PARAM         28
#define CHT_TRANS_TD            29
#define CHT_TRANS_YB            3
#define CHT_HOUSE_TRHEAD        31
#define CHT_TRANS_ID            32
#define CHT_TRANS_NOTE          33
#define PR__ECTR                1
#define PR__EDAT                2
#define PR__EHED                3
#define PR__EMHED               4
#define PR__EPAR                5
#define PR__EPOS                6
#define PR__ETAB                7
#define PR__ETEXT               8
#define PR__LIN                 9
#define PR__SCTR                10
#define PR__SDAT                11
#define PR__SHED                12
#define PR__SMHED               13
#define PR__SPAR                14
#define PR__SPOS                15
#define PR__STAB                16
#define PR__STEXT               17
#define PR__TAB                 18
#define ST__MONTH               32
#define ST__SIGN                45
#define ST__PLANET              58
#define ST__EARTH               100
#define ST__NUMBERS             101
#define ST__ASPECTS             116
#define ST__SIGN3               129
#define ST__ERROR               141
#define ST__HOUSE_MODES         146
#define ST__RECT_METH           156
#define ST__SIDE_TROP           161 
#define ST__RETROGRADE          163
#define TR__AFFECTS             166
#define CHPR_HOUSE              10
#define CHPR_ASPECT             11
#define CHPR_SIGN               12
#define CHPR_SIGN_HOUSE         13
#define CHPR_HSE_CUSP_SIGN      14
#define CHPR_PLAN_HOUSE         15
#define CHPR_PLAN_SIGN          16
#define CHPR_RESULT             17
#define ST__ARABN               166
#define ST__FIXEDN              166
#define ST_PROBRES              166
#define ST__MESSIER              166
#define CHSO_HEAD               28
#define CH__DIAL                35
#define CH__HARMONIC            36
#define CHSO_ASPECT             37
#define CHSO_DATA               38